name: Orchestrator

on:
  release:
    types: [deleted]

jobs:
  other-job:
    name: Other    
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo '${{ github.event_name }}' 
        echo '${{ github.event.action }}' 
    
    