name: Orchestrator

on:
  release:
    types: [created, deleted, edited, prereleased, published, released, unpublished]

jobs:
  prerelease-job:
    name: Prereleasing    
    if: github.event_name == 'release' && github.event.action == 'prereleased'
    runs-on: ubuntu-latest
    steps:    
     - run: echo '${{ toJSON(job) }}'
      
  release-job:
    name: Releasing    
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
     - run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV 
      
    
    