name: Published Orchestrator
run-name: Published Orchestrator (${{ github.event.action }}) 

on:
  release:
    types: [published]

jobs:
  other-job:
    name: Other    
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo '${{ github.event_name }}' 
        echo '${{ github.event.action }}' 
    
    